added spot_price value for node_pools
sighupio/fury-eks-installer pull request #19
Opened 2021-06-01 09:46 UTC by lzecca78

This is the third missing piece from the other 2 pr I did (https://github.com/sighupio/furyctl/pull/43 and https://github.com/sighupio/fury-kubernetes-aws/pull/51), that allows covering all the spots behind the spot-instance capability feature.
Feedbacks are welcome! 🙏

2021-06-01 10:36 UTC, angelbarrera92 commented on example/main.tf
> +output "node_pools" {
Remove this piece of code if is not used

2021-06-01 10:36 UTC, angelbarrera92 commented on modules/eks/output.tf
> +output "parsed_node_pool" {
Same here

2021-06-07 06:47 UTC, angelbarrera92 commented
I suggest to think about the interface of the new "spot" feature.

Would it makes sense something like:

```
node_pools = [
{
min_size = 1
max_size = 2
...
spot = {
  enable = true # Require in EKS, GKE, AKS
  price = 0.11231223 # Require only in EKS
}
}
]
```

I know in azure and gke they don't need the `price` but it required to configure the right attribute. This way, we can maintain the same interface across cloud (aks,gke,eks) installers.

What do you think?

2021-06-07 07:02 UTC, nutellinoit commented
Is price mandatory? Usually you use the AWS default, see https://github.com/sighupio/fury-kubernetes-aws/blob/master/modules/aws-kubernetes/kube-worker-spot.tf (there is no price here).

If you set the price, and aws increases the price, your instances will no more start up

2021-06-07 07:10 UTC, lzecca78 commented
@angelbarrera92 ... I really don't get it... the only entry point in fury for piloting the setup is the yaml, so, why make a "common interface" also in Terraform that is the implementation? It makes no sense because in the implementation you only leave the real needed parameter.... No need to maintain parameters that the implementation doesn't need

2021-06-07 07:12 UTC, lzecca78 commented
@nutellinoit, we are using in our module the babenko eks official module: https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/docs/spot-instances.md#using-launch-configuration .
Our implementation follows that launch configuration setup, so the only way to do that is to pass the spot_price, as the documentation says

2021-06-07 07:15 UTC, angelbarrera92 commented
> @angelbarrera92 ... I really don't get it... the only entry point in fury for piloting the setup is the yaml, so, why make a "common interface" also in Terraform that is the implementation? It makes no sense because in the implementation you only leave the real needed parameter.... No need to maintain parameters that the implementation doesn't need

Because this was the main design decision we made with the cloud installers.

2021-06-07 07:19 UTC, nutellinoit commented
> @nutellinoit, we are using in our module the babenko eks official module: https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/docs/spot-instances.md#using-launch-configuration .
> Our implementation follows that launch configuration setup, so the only way to do that is to pass the spot_price, as the documentation says

Understood. What happens when the spot instances costs more than the price set?

2021-06-07 07:19 UTC, lzecca78 commented
>Because this was the main design decision we made with the cloud installers.
Ah ok
![](https://www.meme-arsenal.com/memes/6631bd9edd4635fbe3395e9f84b73f41.jpg)

2021-06-07 07:44 UTC, lzecca78 commented
@nutellinoit :
> The spot_price is set to the on-demand price so that the spot instances will run as long as they are the cheaper.

As far as I understood, (and this is what I know regarding the spot instances), you'll be notified with a notification/event and that the instance will be shut down.
This is the nature of the spot instance. But for this reason, I made the deployment of the aws-node-termination-handler: https://github.com/sighupio/fury-kubernetes-aws/pull/51

2021-07-02 10:44 UTC, lnovara approved these changes
@lzecca78 If I understand correctly, to create spot instances for a given node pool I just need to specify the `spot_instance_price` parameter and I can leave it empty to get the "default" price, right?

2021-07-02 11:00 UTC, lzecca78 commented
mmmm this is not how the babenko terraform module works afaik: https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/docs/spot-instances.md#using-launch-configuration as you can see here @lnovara, the discriminant parameter is to set a value in the parameter `spot_price` otherwise it will be considered as a normal instance. So going back to the furyctl implementation: when you need to inject the spot instance parameter: https://github.com/sighupio/furyctl/pull/43/files#diff-9dfba49c7818625d480d2ebe3e00b2ef393faa4fbb30aa3bd9f55ef53416cb39R39 there is a struct that need to filled up in both its parameters (bool and price) when you're on EKS, while for GKE you only need the boolean.

2021-07-07 11:12 UTC, nutellinoit requested changes
Can we put a default price on spot instance, let's say `100` euros per hour, if we enable nodegroup as spot?
I think AWS will still use the lower price possible for the instances.

Or better, can we get the price with a `data` from the instance sizing?

I would like to avoid putting `spot_instance_price`

2021-07-07 13:31 UTC, nutellinoit approved these changes
Very little fix, and the changes are now LGTM ❤️ ❤️ ❤️ ❤️ ❤️

2021-07-07 13:31 UTC, nutellinoit commented on modules/eks/eks.tf
> +      // adding 20% more of get price in order to avoid price volatily
We can remove this comment here

2021-08-04 07:13 UTC, merged