Switch from launch configurations to launch templates
sighupio/fury-eks-installer pull request #42
Opened 2022-12-14 11:05 UTC by lnovara

Given the upcoming [deprecation of launch configuration](https://aws.amazon.com/blogs/compute/amazon-ec2-auto-scaling-will-no-longer-add-support-for-new-ec2-features-to-launch-configurations/), we need to migrate to launch templates. As you can see, the [underlying Terraform module](https://github.com/terraform-aws-modules/terraform-aws-eks) already supports launch templates and the changes needed to the installer are trivial but making the switch for existing clusters would imply downtime as all the nodes need to be destroyed and then recreated.

How do we want to manage the migration? I think the heavy lifting should be done by furyctl (I'm trying to figure how) but we need an installer that can support but launch configuration and launch templates for the sake of migration.

What are your thoughts on the topic?

Closes #39

2022-12-14 11:08 UTC, nutellinoit commented
Maybe a conditional dynamic block with a parameter that pilot if we are using `worker_groups` or `worker_groups_launch_template` ?

https://codeinthehole.com/tips/conditional-nested-blocks-in-terraform/

2022-12-14 16:25 UTC, lnovara commented
In the end, dynamic blocks where not needed. I managed to achieve something meaningful using just conditionals. Obviously, in the installer, it's up to the user to select the value and apply the correct steps to migrate from launch configurations to launch templates.

2022-12-15 08:59 UTC, ralgozino commented
Hi @lnovara 
From the announcement you linked, it seems that the Auto Scaling Groups can be switched from launch configuration to launch templates without needing to recreate them.

Maybe the only thing to have in mind is the order that the operations are performed (first add the launch template field and then remove the launch configuration)

I wonder if changing the value makes Terraform recreate the ASG or if it is smart enough, did you test this by any chance?

Thanks!

2022-12-15 17:51 UTC, ralgozino requested changes
After reviewing together the missing bits of the PR are:

- rename `node_pool_kind` to `node_pool_launch_kind`
- add a markdown file with the procedure to follow to migrate from one kind to the other

2022-12-16 11:13 UTC, omissis approved these changes

2022-12-16 11:26 UTC, lnovara commented
We also tried to make the transition as transparent as possible to the end user and without any downtime, but that migration path involved doing nasty stuff such as manually editing the Terraform state so, even if we had some success, we gave up in that route.

2022-12-16 14:26 UTC, ralgozino requested changes

2022-12-16 14:26 UTC, ralgozino commented on docs/UPGRADE-1.11.md
> +# Upgrade from v1.10.x to v1.11.x
1.10 was a draft and has not been released yet, This should read 

```markdown
# Upgrade from v1.9.x to v1.10.x
```

2022-12-16 14:26 UTC, ralgozino commented on docs/UPGRADE-1.11.md
> +
For some reason I can't make code suggestions 🤷 
I'll add this bit here:

```markdown
- Selecting `launch_configuration` in existing Fury clusters would change nothing.
- Selecting `launch_template` for existing clusters will delete the current node pools and create new ones.
- Selecting `both` for existing clusters will create new node pools that use the `launch_templates` and leave the old with `launch_configuration` intact.

Continue reading for how to migrate an existing cluster from `launch_configuration` to `launch_templates`.

```

2022-12-16 14:26 UTC, ralgozino commented on docs/UPGRADE-1.11.md
> +1. Cordon all the existing nodes created using launch configurations using `kubectl cordoni <node_name>`.
there's a typo in the command `cordoni` instead of `cordon` 😄 🇮🇹

2022-12-16 14:26 UTC, ralgozino commented on docs/UPGRADE-1.11.md
> +5. Change `node_pools_launch_kind` to `"launch_templates"` in your Terraform module configuration and apply.
I'd add a comment here saying that this will effectively delete the old nodes.

2022-12-16 22:39 UTC, ralgozino approved these changes
:shipit:

2022-12-18 22:07 UTC, merged